[project]
name = "source-seeking-algorithms"
version = "0.1.0"
description = "Visulizing Source Seeking algorithms and comparing their performances"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "ruff>=0.8.6",
]
